version: '2'
services:
  api:
    build: ./docker/app
    image: "apiproject"
    volumes:
      - ${PWD}/src/app:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - "yarn"
      - "redis"
    links:
      - redis:redis

  yarn:
    build: ./docker/yarn
    image: "yarn"
    volumes:
      - ${PWD}/src/app:/app

  redis:
    image: redis:latest
    ports:
      - 26379:6379
